//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAddress
    {
        public long AccountId { get; set; }
        public long AdapterSettingId { get; set; }
        public string CreditAddress { get; set; }
        public string DebitAddress { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AdapterSetting AdapterSetting { get; set; }
        public virtual AdapterSetting AdapterSetting1 { get; set; }
    }
}
