//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Transaction = new HashSet<Transaction>();
        }
    
        public long Id { get; set; }
        public string TransactionAccount { get; set; }
        public long EnterpriseAdapterId { get; set; }
        public long CryptoAdapterId { get; set; }
        public string CreditAddress { get; set; }
        public string DebitAddress { get; set; }
    
        public virtual CryptoAdapter CryptoAdapter { get; set; }
        public virtual EnterpriseAdapter EnterpriseAdapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
