//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adapter()
        {
            this.BusinessAdapter = new HashSet<BusinessAdapter>();
            this.CryptoAdapter = new HashSet<CryptoAdapter>();
            this.EnterpriseAdapter = new HashSet<EnterpriseAdapter>();
            this.JobDefinition = new HashSet<JobDefinition>();
            this.JobDefinition1 = new HashSet<JobDefinition>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int DirectionId { get; set; }
        public long UserProfileId { get; set; }
        public int StatusId { get; set; }
        public int AdapterTypeItemId { get; set; }
    
        public virtual AdapterTypeItem AdapterTypeItem { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusinessAdapter> BusinessAdapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CryptoAdapter> CryptoAdapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterpriseAdapter> EnterpriseAdapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDefinition> JobDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDefinition> JobDefinition1 { get; set; }
    }
}
