//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockTransaction
    {
        public long Id { get; set; }
        public long BlockId { get; set; }
        public string TxHash { get; set; }
    
        public virtual Block Block { get; set; }
    }
}
