//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Block()
        {
            this.BlockTransaction = new HashSet<BlockTransaction>();
        }
    
        public long Id { get; set; }
        public long BlockNumber { get; set; }
        public long JobTimelineId { get; set; }
        public System.DateTime BlockTime { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual JobTimeline JobTimeline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockTransaction> BlockTransaction { get; set; }
    }
}
