//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseAdapterTableColumn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnterpriseAdapterTableColumn()
        {
            this.EnterpriseAdapterTableColumn1 = new HashSet<EnterpriseAdapterTableColumn>();
        }
    
        public long Id { get; set; }
        public long EnterpriseAdapterTableId { get; set; }
        public string ColumnName { get; set; }
        public bool IsForeignKey { get; set; }
        public int DataTypeId { get; set; }
        public string RelatedTableName { get; set; }
        public bool IsPrimaryKey { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<int> PropertyNameId { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual EnterpriseAdapterTable EnterpriseAdapterTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterpriseAdapterTableColumn> EnterpriseAdapterTableColumn1 { get; set; }
        public virtual EnterpriseAdapterTableColumn EnterpriseAdapterTableColumn2 { get; set; }
        public virtual PropertyName PropertyName { get; set; }
    }
}
