//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseAdapterProperty
    {
        public long EnterpriseAdapterId { get; set; }
        public long PropertyId { get; set; }
        public string Value { get; set; }
    
        public virtual EnterpriseAdapter EnterpriseAdapter { get; set; }
        public virtual Property Property { get; set; }
    }
}
