//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobDefinition()
        {
            this.JobDefinitionProperty = new HashSet<JobDefinitionProperty>();
            this.Schedule = new HashSet<Schedule>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long From { get; set; }
        public long To { get; set; }
        public bool Retry { get; set; }
        public int NumberOfRetry { get; set; }
        public long UserProfileId { get; set; }
    
        public virtual Adapter Adapter { get; set; }
        public virtual Adapter Adapter1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDefinitionProperty> JobDefinitionProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
