//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobHistory
    {
        public long Id { get; set; }
        public long JobTimelineId { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int JobStatusId { get; set; }
        public string Message { get; set; }
    
        public virtual JobStatus JobStatus { get; set; }
        public virtual JobTimeline JobTimeline { get; set; }
    }
}
