//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrometheusEntities : DbContext
    {
        public PrometheusEntities()
            : base("name=PrometheusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Adapter> Adapter { get; set; }
        public virtual DbSet<AdapterMapping> AdapterMapping { get; set; }
        public virtual DbSet<AdapterType> AdapterType { get; set; }
        public virtual DbSet<AdapterTypeItem> AdapterTypeItem { get; set; }
        public virtual DbSet<AdapterTypeItemProperty> AdapterTypeItemProperty { get; set; }
        public virtual DbSet<Block> Block { get; set; }
        public virtual DbSet<BlockTransaction> BlockTransaction { get; set; }
        public virtual DbSet<BusinessAdapter> BusinessAdapter { get; set; }
        public virtual DbSet<BusinessFile> BusinessFile { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CryptoAdapter> CryptoAdapter { get; set; }
        public virtual DbSet<CryptoAdapterProperty> CryptoAdapterProperty { get; set; }
        public virtual DbSet<DataType> DataType { get; set; }
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<EnterpriseAdapter> EnterpriseAdapter { get; set; }
        public virtual DbSet<EnterpriseAdapterProperty> EnterpriseAdapterProperty { get; set; }
        public virtual DbSet<EnterpriseAdapterTable> EnterpriseAdapterTable { get; set; }
        public virtual DbSet<EnterpriseAdapterTableColumn> EnterpriseAdapterTableColumn { get; set; }
        public virtual DbSet<Exchange> Exchange { get; set; }
        public virtual DbSet<JobDefinition> JobDefinition { get; set; }
        public virtual DbSet<JobDefinitionAdapterTypeItemProperty> JobDefinitionAdapterTypeItemProperty { get; set; }
        public virtual DbSet<JobDefinitionProperty> JobDefinitionProperty { get; set; }
        public virtual DbSet<JobHistory> JobHistory { get; set; }
        public virtual DbSet<JobStatus> JobStatus { get; set; }
        public virtual DbSet<JobTimeline> JobTimeline { get; set; }
        public virtual DbSet<Market> Market { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<PropertyName> PropertyName { get; set; }
        public virtual DbSet<PropertyType> PropertyType { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Symbol> Symbol { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<TransactionStatus> TransactionStatus { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
        public virtual DbSet<TransactionTypeAlias> TransactionTypeAlias { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
    }
}
