//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.AdapterTypeItemProperty = new HashSet<AdapterTypeItemProperty>();
            this.CryptoAdapterProperty = new HashSet<CryptoAdapterProperty>();
            this.EnterpriseAdapterProperty = new HashSet<EnterpriseAdapterProperty>();
            this.JobDefinitionAdapterTypeItemProperty = new HashSet<JobDefinitionAdapterTypeItemProperty>();
            this.JobDefinitionProperty = new HashSet<JobDefinitionProperty>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PropertyTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdapterTypeItemProperty> AdapterTypeItemProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CryptoAdapterProperty> CryptoAdapterProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterpriseAdapterProperty> EnterpriseAdapterProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDefinitionAdapterTypeItemProperty> JobDefinitionAdapterTypeItemProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDefinitionProperty> JobDefinitionProperty { get; set; }
        public virtual PropertyType PropertyType { get; set; }
    }
}
