//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symbol
    {
        public int Id { get; set; }
        public int MarketId { get; set; }
        public string Name { get; set; }
        public int StatusId { get; set; }
    
        public virtual Market Market { get; set; }
        public virtual Status Status { get; set; }
    }
}
