//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prometheus.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public long AccountId { get; set; }
        public decimal TransactionAmount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string TransactionHash { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
        public int TransactionStatusId { get; set; }
        public long JobTimelineId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual JobTimeline JobTimeline { get; set; }
        public virtual TransactionStatus TransactionStatus { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
